name: ftda_m01
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.3.1
  - pandas=1.5.2
  - matplotlib=3.6.2
  - scipy=1.9.3
  - spyder
  - pip:
      - adrpy==0.2.5
      - alabaster==0.7.13
      - attrs==22.2.0
      - babel==2.11.0
      - charset-normalizer==3.0.1
      - colorama==0.4.6
      - coverage==7.1.0
      - docutils==0.18.1
      - exceptiongroup==1.1.0
      - idna==3.4
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - nose==1.3.7
      - pluggy==1.0.0
      - pygments==2.14.0
      - pytest==7.2.1
      - requests==2.28.2
      - snowballstemmer==2.2.0
      - sphinx==6.1.3
      - sphinx-rtd-theme==1.2.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tomli==2.0.1
      - urllib3==1.26.14